#!/usr/bin/env bash
# The exact universes behind docs/FALLING_KNIFE.md. Run from this directory; writes ./data/ (gitignored).
set -euo pipefail
cd "$(dirname "$0")"

# Development + v1 held-out universes (chosen before any scoring).
python3 -u fetch.py crypto AAVEUSDT ADAUSDT ATOMUSDT AVAXUSDT BNBUSDT BTCUSDT DOGEUSDT DOTUSDT ETCUSDT ETHUSDT \
  FTTUSDT LINKUSDT LTCUSDT LUNAUSDT MATICUSDT SOLUSDT TRXUSDT UNIUSDT XLMUSDT XRPUSDT
python3 -u fetch.py equity SPY QQQ AAPL MSFT AMZN META NVDA TSLA NFLX JPM BAC C BA INTC AMD WBA PYPL SNAP KRE ZION WAL \
  CMA KEY SCHW GME COIN MSTR BABA EDU PTON ZM DIS KO PG WMT XOM CVX PFE UNH CCL AAL UAL DAL MRNA SMCI IWM GOOGL GS F GM
python3 -u fetch.py fx EURUSD=X GBPUSD=X AUDUSD=X NZDUSD=X USDJPY=X USDCHF=X USDCAD=X EURCHF=X EURJPY=X GBPJPY=X \
  AUDJPY=X EURGBP=X USDTRY=X USDZAR=X USDMXN=X USDBRL=X USDRUB=X USDCNY=X USDINR=X USDARS=X NZDJPY=X CADJPY=X

# Fresh universes: first downloaded only after FROZEN_v2.json / FROZEN_v2_crypto.json were written.
python3 -u fetch.py equity_fresh ORCL CSCO IBM QCOM TXN MU ADBE CRM NKE SBUX MCD LOW TGT COST MMM GE HON LMT DE UPS \
  FDX MS AXP USB PNC MET AIG T VZ CMCSA ABBV MRK LLY BMY GILD AMGN OXY COP SLB HAL DVN FCX NEM AA X CLF RIVN LCID \
  PLTR HOOD SOFI UPST AFRM ROKU SHOP UBER LYFT DASH ABNB NIO XPEV JD PDD BIDU SPOT
python3 -u fetch.py fx_fresh EURSEK=X EURNOK=X USDSEK=X USDNOK=X EURPLN=X USDPLN=X EURHUF=X USDHUF=X EURCZK=X \
  USDSGD=X USDKRW=X USDTHB=X USDIDR=X USDCLP=X USDCOP=X USDPHP=X AUDNZD=X EURAUD=X EURCAD=X GBPCHF=X CHFJPY=X \
  NZDCAD=X USDILS=X GBPAUD=X
python3 -u fetch.py crypto_fresh EOSUSDT BCHUSDT XMRUSDT ZECUSDT DASHUSDT NEOUSDT IOTAUSDT ONTUSDT VETUSDT ALGOUSDT \
  FILUSDT THETAUSDT ICXUSDT QTUMUSDT ZILUSDT BATUSDT KNCUSDT SNXUSDT COMPUSDT CRVUSDT MKRUSDT EGLDUSDT NEARUSDT \
  SANDUSDT MANAUSDT AXSUSDT CHZUSDT ENJUSDT HBARUSDT XTZUSDT
